version: "3.8"

services:
  app:
    image: nullstone/phoenix:local
    volumes:
      - .:/app
      - deps:/app/deps
    ports:
      - "4000:9000"
    environment:
      - NULLSTONE_ENV=local
      - POSTGRES_URL=postgres://acme:acme@db:5432/acme
    depends_on:
      - db

  db:
    image: "postgres:13"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=acme
      - POSTGRES_PASSWORD=acme
      - POSTGRES_DB=acme

volumes:
  deps:
