version: "3.8"

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "4000:4000"
    environment:
      - NULLSTONE_ENV=local
      - POSTGRES_URL=postgres://acme:acme@db:5432/acme
      - DATABASE_URL=postgres://acme:acme@db:5432/acme
    depends_on:
      - db

  db:
    image: "postgres:13"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=acme
      - POSTGRES_PASSWORD=acme
      - POSTGRES_DB=acme
