version: "0.1"

subdomains:
  phoenix-subdomain:
    module: nullstone/autogen-aws-subdomain

datastores:
  postgres:
    module: nullstone/aws-rds-postgres

apps:
  elixir-phoenix-quickstart:
    module: nullstone/aws-fargate-service
    vars:
      cpu: 256
      memory: 512
      port: 80
    capabilities:
      - module: nullstone/rails-cookies
      - module: nullstone/aws-postgres-access
        connections:
          postgres: postgres
      - module: nullstone/aws-load-balancer
        connections:
          subdomain: phoenix-subdomain
